[package]
name = "sky-gateway"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "The Sky framework HTTP gateway binary"
readme.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
sky-proto = { workspace = true }
sky-runtime = { workspace = true }
sky-worker = { workspace = true }

tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

axum = { workspace = true }
tower-http = { workspace = true }

humantime-serde = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
jsonschema = { workspace = true }
thiserror = { workspace = true }
